# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: nc5ng.org
email: info@nc5ng.org
description: |
  This is a fork, and private project, nc5ng.org is not affiliated with the National Geodetic Survey.`

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nc5ng.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  nc5ng
google_analytics: UA-115513288-1

copyright: '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> <br /> <p> This webpage is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.</p>'

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_whitsheets"
      type: "whitesheets"
    values:
      layout: "whitesheet"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
        
      
## Collections Defined Here
collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true
  whitesheets:
    permalink: /whitesheets/:title
    output: true
  projects:
    permalink: /projects/:title
    output: true


# Build settings
markdown: kramdown
#theme: none
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


css_path: /assets/styles
site_css: /assets/styles/site.css


header_pages:
  - projects.html
  - posts.html
  - whitesheets.html
  - about.md